// This is an autogenerated file from Firebase Genkit.
'use server';
/**
 * @fileOverview A weather-based recommendation AI agent.
 *
 * - getWeatherRecommendation - A function that handles the weather recommendation process.
 * - WeatherRecommendationInput - The input type for the getWeatherRecommendation function.
 * - WeatherRecommendationOutput - The return type for the getWeatherRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendationSchema = z.object({
  quick: z.string().describe('A very short, quick-glance recommendation with emojis.'),
  detailed: z.string().describe('A more detailed explanation for the recommendation.'),
  icon: z.enum(['shirt', 'umbrella', 'bus', 'bike', 'walk', 'car', 'alert', 'sun', 'wind', 'mask']).describe('An icon representing the recommendation category.'),
});

const WeatherRecommendationInputSchema = z.object({
  weatherCondition: z.string().describe('The current weather condition (e.g., rainy, sunny, cloudy).'),
  temperature: z.number().describe('The current temperature in Celsius.'),
  humidity: z.number().describe('The current humidity percentage.'),
  windSpeed: z.number().describe('The current wind speed in km/h.'),
  rainChance: z.number().describe('The chance of rain in percentage.'),
  uvIndex: z.number().optional().describe('The UV index.'),
  preferences: z.object({
    agriculture: z.boolean().describe('Whether the user is interested in agriculture recommendations.'),
    dress: z.boolean().describe('Whether the user is interested in dress recommendations.'),
    transport: z.boolean().describe('Whether the user is interested in transport recommendations.'),
    usualTravel: z.enum(['bike', 'car', 'walk', 'public transport']).optional().describe('The user\'s preferred mode of travel.'),
  }).describe('The user preferences for recommendations.'),
});
export type WeatherRecommendationInput = z.infer<typeof WeatherRecommendationInputSchema>;

const WeatherRecommendationOutputSchema = z.object({
  outfit: RecommendationSchema.optional(),
  travel: RecommendationSchema.optional(),
  safety: z.array(RecommendationSchema).optional(),
  agriculture: RecommendationSchema.optional(),
});
export type WeatherRecommendationOutput = z.infer<typeof WeatherRecommendationOutputSchema>;

export async function getWeatherRecommendation(input: WeatherRecommendationInput): Promise<WeatherRecommendationOutput> {
  return weatherRecommendationFlow(input);
}

const weatherRecommendationPrompt = ai.definePrompt({
  name: 'weatherRecommendationPrompt',
  input: {schema: WeatherRecommendationInputSchema},
  output: {schema: WeatherRecommendationOutputSchema},
  prompt: `You are a personalized weather advisor. Based on the current weather conditions and the user's preferences, provide relevant recommendations for outfits, travel, safety, and agriculture.
For each recommendation, provide a 'quick' summary (with relevant emojis), a 'detailed' explanation, and a relevant 'icon'.

Current Weather:
Condition: {{{weatherCondition}}}
Temperature: {{{temperature}}}°C
Humidity: {{{humidity}}}%
Wind Speed: {{{windSpeed}}} km/h
Chance of Rain: {{{rainChance}}}%
{{#if uvIndex}}UV Index: {{{uvIndex}}}{{/if}}

User Preferences:
{{#if preferences.dress}}Outfit advice: Yes{{/if}}
{{#if preferences.transport}}
Travel advice: Yes
  {{#if preferences.usualTravel}}Preferred travel: {{{preferences.usualTravel}}}{{/if}}
{{/if}}
{{#if preferences.agriculture}}Agriculture advice: Yes{{/if}}

For the 'safety' recommendations, always check for high UV index, extreme temperatures, high wind, or rain. Provide specific alerts for each. For example:
- If UV index is high (>=6), suggest using sunscreen. Use 'sun' icon.
- If air quality is poor (if data is available), suggest wearing a mask. Use 'mask' icon.
- For other general safety alerts, use the 'alert' icon.

Generate recommendations based on these inputs. If a preference is disabled, do not generate a recommendation for it.

Example Output Structure:
{
  "outfit": { "quick": "Wear light cotton clothes 👕", "detailed": "It's hot and humid, so light fabrics are best.", "icon": "shirt" },
  "travel": { "quick": "Take a cab 🚖", "detailed": "High chance of rain and traffic, a cab is a safe bet.", "icon": "car" },
  "safety": [
    { "quick": "High UV Index ☀️", "detailed": "UV index is high, remember to use sunscreen.", "icon": "sun" }
  ]
}
`,
});

const weatherRecommendationFlow = ai.defineFlow(
  {
    name: 'weatherRecommendationFlow',
    inputSchema: WeatherRecommendationInputSchema,
    outputSchema: WeatherRecommendationOutputSchema,
  },
  async input => {
    const {output} = await weatherRecommendationPrompt(input);
    return output!;
  }
);
